#pragma once
#include <SDL2/SDL.h>

typedef enum {
  A = SDL_SCANCODE_A,
  S = SDL_SCANCODE_S,
  D = SDL_SCANCODE_D,
  F = SDL_SCANCODE_F,
  H = SDL_SCANCODE_H,
  J = SDL_SCANCODE_J,
  K = SDL_SCANCODE_K,
  L = SDL_SCANCODE_L,
  E = SDL_SCANCODE_E,
  W = SDL_SCANCODE_W,
  U = SDL_SCANCODE_U,
  I = SDL_SCANCODE_I
} NOTE_KEYS;

typedef enum {

} CONFIG_KEYS;
